//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int clientid { get; set; }
        public string clientname { get; set; }
        public string phone { get; set; }
        public System.DateTime addtime { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string beizhu { get; set; }
    }
}
