//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class kuwei
    {
        public string kuweiid { get; set; }
        public string kuweiname { get; set; }
        public Nullable<int> warehouseid { get; set; }
        public Nullable<int> kuWeiTypeid { get; set; }
        public string forbidden { get; set; }
        public string defaults { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual kuweiwarehouse kuweiwarehouse { get; set; }
        public virtual kuweitype kuweitype { get; set; }
    }
}
