//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class warehousing_systemEntities : DbContext
    {
        public warehousing_systemEntities()
            : base("name=warehousing_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audit> audit { get; set; }
        public virtual DbSet<bsodd> bsodd { get; set; }
        public virtual DbSet<check> check { get; set; }
        public virtual DbSet<checktype> checktype { get; set; }
        public virtual DbSet<ckodd> ckodd { get; set; }
        public virtual DbSet<cktype> cktype { get; set; }
        public virtual DbSet<clerk> clerk { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<damage> damage { get; set; }
        public virtual DbSet<damagetype> damagetype { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<kuwei> kuwei { get; set; }
        public virtual DbSet<kuweitype> kuweitype { get; set; }
        public virtual DbSet<kuweiwarehouse> kuweiwarehouse { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<move> move { get; set; }
        public virtual DbSet<movetype> movetype { get; set; }
        public virtual DbSet<pdodd> pdodd { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<productmanagement> productmanagement { get; set; }
        public virtual DbSet<register> register { get; set; }
        public virtual DbSet<rkodd> rkodd { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<salesreturn> salesreturn { get; set; }
        public virtual DbSet<salestype> salestype { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<stockmanagement> stockmanagement { get; set; }
        public virtual DbSet<Storagetype> Storagetype { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<supplierleixinBiao> supplierleixinBiao { get; set; }
        public virtual DbSet<thodd> thodd { get; set; }
        public virtual DbSet<unit> unit { get; set; }
        public virtual DbSet<usermode> usermode { get; set; }
        public virtual DbSet<Warehousemanagement> Warehousemanagement { get; set; }
        public virtual DbSet<ykodd> ykodd { get; set; }
    }
}
