//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutStorage
    {
        public int id { get; set; }
        public string ordernum { get; set; }
        public string cusname { get; set; }
        public Nullable<int> cusnum { get; set; }
        public string kuwei { get; set; }
        public string contact { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string ContractOrder { get; set; }
        public Nullable<int> num { get; set; }
        public System.DateTime addtime { get; set; }
        public string cjr { get; set; }
        public Nullable<int> leixing { get; set; }
    }
}
