//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class productmanagement
    {
        public int meteringid { get; set; }
        public string Cpid { get; set; }
        public string commodityname { get; set; }
        public Nullable<int> ceiling { get; set; }
        public Nullable<int> floor { get; set; }
        public string price { get; set; }
        public int productid { get; set; }
        public int metering { get; set; }
        public int warehouseid { get; set; }
        public int clientid { get; set; }
        public string kuWeiTypeName { get; set; }
    
        public virtual client client { get; set; }
        public virtual kuweiwarehouse kuweiwarehouse { get; set; }
        public virtual product product { get; set; }
        public virtual unit unit { get; set; }
        public virtual productmanagement productmanagement1 { get; set; }
        public virtual productmanagement productmanagement2 { get; set; }
        public virtual productmanagement productmanagement11 { get; set; }
        public virtual productmanagement productmanagement3 { get; set; }
    }
}
