//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class productbiao
    {
        public int produid { get; set; }
        public Nullable<int> ordernum { get; set; }
        public string ProductName { get; set; }
        public string BarCode { get; set; }
        public string ProductNum { get; set; }
        public string BatchNum { get; set; }
        public Nullable<double> num { get; set; }
        public Nullable<int> inprice { get; set; }
        public Nullable<double> amount { get; set; }
        public string pici { get; set; }
        public string kuwei { get; set; }
    }
}
