//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int staffid { get; set; }
        public string staffName { get; set; }
        public string iphone { get; set; }
        public Nullable<int> departmentid { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<int> clerkid { get; set; }
        public Nullable<int> logins { get; set; }
    
        public virtual department department { get; set; }
        public virtual role role { get; set; }
        public virtual clerk clerk { get; set; }
    }
}
