//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockmanagement
    {
        public int Inid { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> supplierid { get; set; }
        public Nullable<int> Cpid { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> money { get; set; }
        public Nullable<int> stateid { get; set; }
        public string zdpeople { get; set; }
        public string czfs { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual audit audit { get; set; }
        public virtual rkodd rkodd { get; set; }
        public virtual stockmanagement stockmanagement1 { get; set; }
        public virtual stockmanagement stockmanagement2 { get; set; }
        public virtual Storagetype Storagetype { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
