//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehousemanagement
    {
        public int ckid { get; set; }
        public Nullable<int> cktypeid { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<int> correlationid { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> money { get; set; }
        public Nullable<int> stateid { get; set; }
        public string czfs { get; set; }
        public string zdpeople { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual audit audit { get; set; }
        public virtual ckodd ckodd { get; set; }
        public virtual cktype cktype { get; set; }
        public virtual client client { get; set; }
    }
}
