//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.tdxm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehousemanagement
    {
        public int ckid { get; set; }
        public Nullable<int> cktypeid { get; set; }
        public string supplierid { get; set; }
        public Nullable<int> correlationid { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> money { get; set; }
        public Nullable<int> stateid { get; set; }
        public string czfs { get; set; }
        public string zdpeople { get; set; }
        public System.DateTime AddTime { get; set; }
        public string ProductName { get; set; }
        public string BarCode { get; set; }
        public string LocalNum { get; set; }
        public Nullable<double> OutPrice { get; set; }
        public Nullable<double> Amount { get; set; }
        public string BatchNum { get; set; }
        public Nullable<int> meteringid { get; set; }
        public string pici { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public string khname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string lxr { get; set; }
        public string beizhu { get; set; }
        public string guige { get; set; }
    
        public virtual audit audit { get; set; }
        public virtual cktype cktype { get; set; }
    }
}
